In [1]:
import pandas as pd
import pickle
import numpy as np

In [2]:
matches = pickle.load(open('dataset_level1.pkl','rb'))

In [3]:
matches

,innings,info.dates,info.outcome.winner,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.city
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-17],Sri Lanka,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Melbourne Cricket Ground,1,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-19],Sri Lanka,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[SD Fry, SJ Nogajski]","Simonds Stadium, South Geelong",2,Victoria
2,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-22],Australia,[A Zampa],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Adelaide Oval,3,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",[2016-09-05],Hong Kong,NaN,"[Ireland, Hong Kong]",bat,Hong Kong,"[R Black, AJ Neill]","Bready Cricket Club, Magheramason",4,Londonderry
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2016-06-18],Zimbabwe,[E Chigumbura],"[Zimbabwe, India]",field,India,"[TJ Matibiri, RB Tiffin]",Harare Sports Club,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1427,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-03-04],Pakistan,[Umar Akmal],"[Pakistan, Sri Lanka]",field,Pakistan,"[AK Chaudhary, Enamul Haque]",Shere Bangla National Stadium,1428,Mirpur
1428,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",[2016-03-06],India,[S Dhawan],"[Bangladesh, India]",field,India,"[RSA Palliyaguruge, Shozab Raza]",Shere Bangla National Stadium,1429,Mirpur
1429,"[{'1st innings': {'team': 'Netherlands', 'deli...",[2016-02-03],Netherlands,[Mudassar Bukhari],"[United Arab Emirates, Netherlands]",field,United Arab Emirates,"[CK Nandan, Sarika Prasad]",ICC Academy,1430,Dubai
1430,"[{'1st innings': {'team': 'Australia', 'delive...",[2016-09-06],Australia,[GJ Maxwell],"[Sri Lanka, Australia]",field,Sri Lanka,"[REJ Martinesz, RR Wimalasiri]",Pallekele International Cricket Stadium,1431,NaN
1431,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-09-09],Australia,[GJ Maxwell],"[Sri Lanka, Australia]",bat,Sri Lanka,"[REJ Martinesz, RSA Palliyaguruge]",R Premadasa Stadium,1432,Colombo

In [4]:
# matches.iloc[0]['innings'][0]

In [5]:
matches.dtypes

innings                 object
info.dates              object
info.outcome.winner     object
info.player_of_match    object
info.teams              object
info.toss.decision      object
info.toss.winner        object
info.umpires            object
info.venue              object
match_id                 int64
info.city               object
dtype: object

In [6]:
match_id = []
batting_team = []
teams = []
balls_of_match = []
batsman = []
bowler = []
runs = []
city = []
venue = []
player_of_dismissed = []
player_of_match = []

count = 1
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    count+=1
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball:
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            balls_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            player_of_match.append(row['info.player_of_match'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
data = {
    'match_id': match_id,
    'teams': teams,
    'batting_team': batting_team,
    'balls': balls_of_match,
    'batsman': batsman,
    'bowler': bowler,
    'runs': runs,
    'player_of_dismissed': player_of_dismissed,
    'city': city,
    'venue': venue,
    'player_of_match' : player_of_match
}

delivery_df = pd.DataFrame(data)

In [7]:
df = delivery_df.copy()

In [8]:
df

,match_id,teams,batting_team,balls,batsman,bowler,runs,player_of_dismissed,city,venue,player_of_match
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne]
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne]
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne]
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne]
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne]
...,...,...,...,...,...,...,...,...,...,...,...
116542,964,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,[GJ Maxwell]
116543,964,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,[GJ Maxwell]
116544,964,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,[GJ Maxwell]
116545,964,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,[GJ Maxwell]
116546,964,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,[GJ Maxwell]

In [9]:
df['player'] = df['player_of_match'].apply(lambda x: x[0] if isinstance(x, list) else x)
df['player'] = df['player'].str.strip('[]')
df

,match_id,teams,batting_team,balls,batsman,bowler,runs,player_of_dismissed,city,venue,player_of_match,player
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne],DAS Gunaratne
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne],DAS Gunaratne
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne],DAS Gunaratne
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne],DAS Gunaratne
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,[DAS Gunaratne],DAS Gunaratne
...,...,...,...,...,...,...,...,...,...,...,...,...
116542,964,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,[GJ Maxwell],GJ Maxwell
116543,964,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,[GJ Maxwell],GJ Maxwell
116544,964,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,[GJ Maxwell],GJ Maxwell
116545,964,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,[GJ Maxwell],GJ Maxwell
116546,964,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,[GJ Maxwell],GJ Maxwell

In [10]:
df.player.isnull().value_counts()

player
False    105403
True      11144
Name: count, dtype: int64

In [11]:
df.drop(columns=['player_of_match'],inplace=True)

In [12]:
df = df.rename(columns={'player': 'player_of_match'})
df

,match_id,teams,batting_team,balls,batsman,bowler,runs,player_of_dismissed,city,venue,player_of_match
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,DAS Gunaratne
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,DAS Gunaratne
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne
...,...,...,...,...,...,...,...,...,...,...,...
116542,964,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,GJ Maxwell
116543,964,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,GJ Maxwell
116544,964,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,GJ Maxwell
116545,964,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,GJ Maxwell
116546,964,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,GJ Maxwell

In [13]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [14]:
df['bowling_team'] = df.apply(bowl,axis=1)
df

,match_id,teams,batting_team,balls,batsman,bowler,runs,player_of_dismissed,city,venue,player_of_match,bowling_team
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...,...,...
116542,964,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,GJ Maxwell,Australia
116543,964,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,GJ Maxwell,Australia
116544,964,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,GJ Maxwell,Australia
116545,964,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,GJ Maxwell,Australia
116546,964,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,GJ Maxwell,Australia

In [15]:
df.drop(columns=['teams'],inplace=True)

In [16]:
team=[
    'India',
    'Pakistan',
    'South Africa',
    'Australia',
    'New Zealand',
    'England',
    'Sri Lanka',
    'Bangladesh',
    'Afghanistan',
    'West Indies'
]

In [17]:
df = df[df['batting_team'].isin(team)]
df = df[df['bowling_team'].isin(team)]

In [18]:
df

,match_id,batting_team,balls,batsman,bowler,runs,player_of_dismissed,city,venue,player_of_match,bowling_team
0,2,Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
1,2,Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
3,2,Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
4,2,Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...,...
116542,964,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,GJ Maxwell,Australia
116543,964,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,GJ Maxwell,Australia
116544,964,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,GJ Maxwell,Australia
116545,964,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,GJ Maxwell,Australia
116546,964,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,GJ Maxwell,Australia

In [19]:
df.isnull().sum()

match_id                  0
batting_team              0
balls                     0
batsman                   0
bowler                    0
runs                      0
player_of_dismissed       0
city                   8671
venue                     0
player_of_match        1172
bowling_team              0
dtype: int64

In [20]:
df[df.city.isnull()]

,match_id,batting_team,balls,batsman,bowler,runs,player_of_dismissed,city,venue,player_of_match,bowling_team
0,2,Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
1,2,Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
3,2,Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
4,2,Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,DAS Gunaratne,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...,...
116416,963,Australia,19.2,GJ Maxwell,NLTC Perera,1,0,NaN,Pallekele International Cricket Stadium,GJ Maxwell,Sri Lanka
116417,963,Australia,19.3,TM Head,NLTC Perera,4,0,NaN,Pallekele International Cricket Stadium,GJ Maxwell,Sri Lanka
116418,963,Australia,19.4,TM Head,NLTC Perera,4,0,NaN,Pallekele International Cricket Stadium,GJ Maxwell,Sri Lanka
116419,963,Australia,19.5,TM Head,NLTC Perera,6,0,NaN,Pallekele International Cricket Stadium,GJ Maxwell,Sri Lanka
116420,963,Australia,19.6,TM Head,NLTC Perera,0,TM Head,NaN,Pallekele International Cricket Stadium,GJ Maxwell,Sri Lanka

In [21]:
df[df.city.isnull()].venue.value_counts()

venue
Dubai International Cricket Stadium        3092
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sharjah Cricket Stadium                     249
Sylhet International Cricket Stadium        128
Carrara Oval                                 64
Name: count, dtype: int64

In [22]:
df.venue.value_counts()

venue
Shere Bangla National Stadium          3420
Dubai International Cricket Stadium    3092
R Premadasa Stadium                    2983
New Wanderers Stadium                  2819
Eden Park                              2655
                                       ...
Senwes Park                             122
Subrata Roy Sahara Stadium              121
Sardar Patel Stadium, Motera            121
Hagley Oval                             121
Carrara Oval                             64
Name: count, Length: 95, dtype: int64

In [23]:
cities = np.where(df.city.isnull(),df.venue.str.split().apply(lambda x : x[0]),df.city)
df.city = cities

In [24]:
df.isnull().sum()

match_id                  0
batting_team              0
balls                     0
batsman                   0
bowler                    0
runs                      0
player_of_dismissed       0
city                      0
venue                     0
player_of_match        1172
bowling_team              0
dtype: int64

In [25]:
df.drop(columns=['venue'],inplace=True)

In [26]:
df.city.value_counts()[df.city.value_counts()>600]

city
Colombo            4208
Mirpur             3420
Johannesburg       3331
Dubai              3092
Auckland           2655
Cape Town          2369
London             2106
Pallekele          2066
Barbados           2050
Sydney             1579
Melbourne          1574
Durban             1520
St Lucia           1487
Wellington         1475
Lauderhill         1238
Hamilton           1219
Centurion          1189
Manchester         1144
Abu Dhabi          1099
Mumbai              995
Nottingham          991
Southampton         987
Mount Maunganui     938
Chittagong          868
Kolkata             844
Lahore              748
Delhi               739
Nagpur              735
Cardiff             730
Chandigarh          627
Adelaide            623
Bangalore           620
St Kitts            618
Christchurch        614
Trinidad            611
Name: count, dtype: int64

In [27]:
eligibal_cities = df.city.value_counts()[df.city.value_counts()>600].index.tolist()
df = df[df.city.isin(eligibal_cities)]
df

,match_id,batting_team,balls,batsman,bowler,runs,player_of_dismissed,city,player_of_match,bowling_team
0,2,Australia,0.1,AJ Finch,SL Malinga,0,0,Melbourne,DAS Gunaratne,Sri Lanka
1,2,Australia,0.2,AJ Finch,SL Malinga,0,0,Melbourne,DAS Gunaratne,Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,1,0,Melbourne,DAS Gunaratne,Sri Lanka
3,2,Australia,0.4,M Klinger,SL Malinga,2,0,Melbourne,DAS Gunaratne,Sri Lanka
4,2,Australia,0.5,M Klinger,SL Malinga,0,0,Melbourne,DAS Gunaratne,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...
116542,964,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,GJ Maxwell,Australia
116543,964,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,GJ Maxwell,Australia
116544,964,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,GJ Maxwell,Australia
116545,964,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,GJ Maxwell,Australia
116546,964,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,GJ Maxwell,Australia

In [29]:
eligibal_cities

['Colombo',
 'Mirpur',
 'Johannesburg',
 'Dubai',
 'Auckland',
 'Cape Town',
 'London',
 'Pallekele',
 'Barbados',
 'Sydney',
 'Melbourne',
 'Durban',
 'St Lucia',
 'Wellington',
 'Lauderhill',
 'Hamilton',
 'Centurion',
 'Manchester',
 'Abu Dhabi',
 'Mumbai',
 'Nottingham',
 'Southampton',
 'Mount Maunganui',
 'Chittagong',
 'Kolkata',
 'Lahore',
 'Delhi',
 'Nagpur',
 'Cardiff',
 'Chandigarh',
 'Adelaide',
 'Bangalore',
 'St Kitts',
 'Christchurch',
 'Trinidad']

In [28]:
output = df[['match_id','batting_team','bowling_team','batsman','balls','runs','player_of_dismissed','player_of_match','city']]
output

,match_id,batting_team,bowling_team,batsman,balls,runs,player_of_dismissed,player_of_match,city
0,2,Australia,Sri Lanka,AJ Finch,0.1,0,0,DAS Gunaratne,Melbourne
1,2,Australia,Sri Lanka,AJ Finch,0.2,0,0,DAS Gunaratne,Melbourne
2,2,Australia,Sri Lanka,AJ Finch,0.3,1,0,DAS Gunaratne,Melbourne
3,2,Australia,Sri Lanka,M Klinger,0.4,2,0,DAS Gunaratne,Melbourne
4,2,Australia,Sri Lanka,M Klinger,0.5,0,0,DAS Gunaratne,Melbourne
...,...,...,...,...,...,...,...,...,...
116542,964,Sri Lanka,Australia,SMSM Senanayake,19.3,1,0,GJ Maxwell,Colombo
116543,964,Sri Lanka,Australia,DM de Silva,19.4,0,0,GJ Maxwell,Colombo
116544,964,Sri Lanka,Australia,DM de Silva,19.5,0,DM de Silva,GJ Maxwell,Colombo
116545,964,Sri Lanka,Australia,SMSM Senanayake,19.6,2,0,GJ Maxwell,Colombo
116546,964,Sri Lanka,Australia,SMSM Senanayake,19.7,1,0,GJ Maxwell,Colombo

In [29]:
pickle.dump(output,open('dataset_level2.pkl','wb'))